source 'https://github.com/CocoaPods/Specs.git'


workspace 'SnapchatKit'
xcodeproj 'SnapchatKit-OSX/SnapchatKit-OSX.xcodeproj'
xcodeproj 'SnapchatKit.xcodeproj'

target 'SnapchatKit_Example', :exclusive => true do
  platform :ios, '9.0'
  link_with 'SnapchatKit_Example'

  pod "SnapchatKit", :path => "../"
end

target 'SnapchatKit-OSX', :exclusive => true do
  xcodeproj 'SnapchatKit-OSX/SnapchatKit-OSX.xcodeproj'
  platform :osx, '10.9'
  link_with 'SnapchatKit-OSX'

  pod 'SnapchatKit', :path => '../'
end

target 'SnapchatKit_Tests', :exclusive => true do
  pod 'SnapchatKit', :path => '../'
end
