#use_frameworks!
#generate_bridge_support!
install! 'cocoapods', :deterministic_uuids => false

workspace 'SnapchatKit'
project 'iOS/SnapchatKit-iOS.xcodeproj'
project 'macOS/SnapchatKit-macOS.xcodeproj'

target :SnapchatKit_iOS do
    platform :ios, '8.0'
    pod 'SnapchatKit', :path => '../'
    project 'iOS/SnapchatKit-iOS.xcodeproj'

    target 'SnapchatKit_iOS_Tests' do
        inherit! :search_paths
    end
end

target :SnapchatKit_macOS do
    platform :osx, '10.9'
    pod 'SnapchatKit', :path => '../'
    project 'macOS/SnapchatKit-macOS.xcodeproj'
end

