source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SnapchatKit_Example', :exclusive => true do
  # link_with 'SnapchatKit_Example', 'SnapchatKit_Tests'
  pod "SnapchatKit", :path => "../"
end

target 'SnapchatKit_Tests', :exclusive => true do
  pod "SnapchatKit", :path => "../"

  
end
